export GameObject from './base/GameObject';
export Canvas from './base/Canvas';
export Scene from './base/Scene';
export Camera from './base/Camera';
export types from './base/types';
export Component from './base/Component';
export components from './components/components';
// export input, {keyCode} from './base/Input';
export Input, {keyCode} from './base-game-object/Input';
export Touch from './base-game-object/Touch';